[tool.poetry]
name = "ch"
version = "0.1.0"
description = ""
authors = ["Merging Futures LLC."]

[tool.poetry.dependencies]
python = "^3.11"
psycopg = "^3.1.12"
psycopg-binary = "^3.1.12"
aws-lambda-powertools = "2.25.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
